- name: Deploy ecommerce
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - nginx
    - role: ecommerce
      nginx_default_sites:
        - ecommerce
