---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role credentials
# 
# Example:
#
# dependencies:
#   - {
#   role: my_role 
#   my_role_var0: "foo"
#   my_role_var1: "bar"
# }
dependencies:
  - role: edx_django_service
    edx_django_service_version: "{{ CREDENTIALS_VERSION }}"
    edx_django_service_name: "{{ credentials_service_name }}"
    edx_django_service_config: "{{ CREDENTIALS_SERVICE_CONFIG }}"
    edx_django_service_debian_pkgs_extra: "{{ credentials_debian_pkgs }}"
    edx_django_service_gunicorn_port: "{{ credentials_gunicorn_port }}"
    edx_django_service_django_settings_module: "{{ CREDENTIALS_DJANGO_SETTINGS_MODULE }}"
    edx_django_service_environment: "{{ credentials_environment }}"
    edx_django_service_migration_environment: "{{ credentials_migration_environment }}"
    edx_django_service_gunicorn_extra: "{{ CREDENTIALS_GUNICORN_EXTRA }}"
    edx_django_service_nginx_port: "{{ CREDENTIALS_NGINX_PORT }}"
    edx_django_service_ssl_nginx_port: "{{ CREDENTIALS_SSL_NGINX_PORT }}"
    edx_django_service_use_python35: false
