---
dependencies:
  - common
  - supervisor
  - role: edx_service
    edx_service_name: "{{ edx_django_service_name }}"
    # TODO After upgrading to Ansible 2, use the combine filter to maintain a default
    # dict, and expand it with service-specific overrides.
    edx_service_config: "{{ edx_django_service_config }}"
    edx_service_repos: "{{ edx_django_service_repos }}"
    edx_service_user: "{{ edx_django_service_user }}"
    edx_service_home: "{{ edx_django_service_home }}"
    edx_service_packages:
      debian: "{{ edx_django_service_debian_pkgs + edx_django_service_debian_pkgs_extra }}"
      redhat: "{{ edx_django_service_redhat_pkgs }}"
