---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role ecommerce
# 
dependencies:
  - role: edx_django_service
    edx_django_service_version: "{{ ECOMMERCE_VERSION }}"
    edx_django_service_name: "{{ ecommerce_service_name }}"
    edx_django_service_config: "{{ ECOMMERCE_SERVICE_CONFIG }}"
    edx_django_service_debian_pkgs_extra: "{{ ecommerce_debian_pkgs }}"
    edx_django_service_gunicorn_port: "{{ ecommerce_gunicorn_port }}"
    edx_django_service_django_settings_module: "{{ ECOMMERCE_DJANGO_SETTINGS_MODULE }}"
    edx_django_service_environment: "{{ ecommerce_environment }}"
    edx_django_service_migration_environment: "{{ ecommerce_migration_environment }}"
    edx_django_service_gunicorn_extra: "{{ ECOMMERCE_GUNICORN_EXTRA }}"
    edx_django_service_nginx_port: "{{ ECOMMERCE_NGINX_PORT }}"
    edx_django_service_ssl_nginx_port: "{{ ECOMMERCE_SSL_NGINX_PORT }}"
    edx_django_service_use_python35: false
  - role: edx_themes
    theme_users:
      - "{{ ecommerce_user }}"
    when: "{{ ECOMMERCE_ENABLE_COMPREHENSIVE_THEMING }}"
